version: '3' 
 
services: 
  backend: 
    build: ./backend 
    ports: 
      - "8080:8080" 
    depends_on: 
      - mysql 
      - neo4j 
      - elasticsearch 
 
  mysql: 
    image: mysql:8.0 
    environment: 
      MYSQL_ROOT_PASSWORD: secret 
      MYSQL_DATABASE: sales 
 
  neo4j: 
    image: neo4j:4.4 
    environment: 
      NEO4J_AUTH: neo4j/secret 
 
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0 
    environment: 
      discovery.type: single-node 
